package:
  name: solvationtoolkit
  version: 0.4.2

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - numpydoc
    - scipy
    - ambermini
    - parmed
    - openmoltools
    - mdtraj
    - packmol
    - netcdf4
    - pandas
    - openmm
    - pytables
  run:
    - python
    - setuptools
    - numpy
    - numpydoc
    - scipy
    - ambermini
    - parmed
    #- libgfortran ==1.0 # [linux]
    - openmoltools
    - mdtraj 
    - packmol
    - netcdf4
    - pandas  
    - openmm
    - pytables 
test:
  requires:
    - nose
    - packmol
  imports:
    - openmoltools
    - parmed
  #commands:
  #  - nosetests openmoltools -v -a '!slow'

about:
  home: https://github.com/mobleylab/solvationtoolkit
  license: MIT
